### ISSUE TITLE
java.lang.NullPointerException in demo.

### ISSUE THREAD

**Issue by DonLiangGit** [orbeus/ReKognition_Android_SDK#1]
DisplayMessageActivity cannot load the JSONObject when the internet is unavailable. I think before calling an activity it needs to be checked the internet connection.

**Comment by tlyalex** [comment]
Could you provide us a code snipper about this?

Sorry for the late response. 

In the mean time, we have released android sdk version 2, I believe it won't have this problem.

And it's much more powerful and easier to use.

It's at https://github.com/orbeus/Rekognition_Android_SDK_2
